name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-bot:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-15-intel, macos-26 ]
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: {% raw %}${{ steps.set-up-homebrew.outputs.gems-path }}{% endraw %}
          key: {% raw %}${{ matrix.os }}{% endraw %}-rubygems-{% raw %}${{ steps.set-up-homebrew.outputs.gems-hash }}{% endraw %}
          restore-keys: {% raw %}${{ matrix.os }}{% endraw %}-rubygems-

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax
      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: bottles_{% raw %}${{ matrix.os }}{% endraw %}
          path: '*.bottle.*'
